# Generated by Django 4.0.4 on 2022-04-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consumer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.wallet'),
        ),
    ]
