# Generated by Django 4.0.4 on 2022-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_consumer_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='access_token',
        ),
        migrations.AddField(
            model_name='foundation',
            name='hex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
